-- Supabase → SQL Editor → New query → вставьте и выполните весь файл.
create table if not exists public.transactions (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 type text not null check(type in ('income','expense','purchase','sale')),
 amount numeric(14,2) not null check(amount>0), note text not null default '',
 date date not null default current_date, created_at timestamptz not null default now()
);
create table if not exists public.debts (
 id bigint generated by default as identity primary key,
 user_id uuid not null references auth.users(id) on delete cascade,
 name text not null, amount numeric(14,2) not null check(amount>0),
 date date not null default current_date, note text not null default '',
 paid boolean not null default false, created_at timestamptz not null default now()
);
alter table public.transactions enable row level security;
alter table public.debts enable row level security;
drop policy if exists "Users manage own transactions" on public.transactions;
create policy "Users manage own transactions" on public.transactions for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
drop policy if exists "Users manage own debts" on public.debts;
create policy "Users manage own debts" on public.debts for all to authenticated using(auth.uid()=user_id) with check(auth.uid()=user_id);
grant select,insert,update,delete on public.transactions to authenticated;
grant select,insert,update,delete on public.debts to authenticated;
grant usage,select on all sequences in schema public to authenticated;
